# Generated by Django 5.1.7 on 2025-03-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='category_id',
            new_name='category',
        ),
    ]
