# Generated by Django 5.1.7 on 2025-03-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_author_post_postimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
    ]
