# Generated by Django 5.1.7 on 2025-03-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Completed')], default='new', max_length=255),
        ),
    ]
