# Generated by Django 5.1.7 on 2025-03-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_images/')),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
            ],
        ),
    ]
