# Generated by Django 5.1.7 on 2025-03-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_team_options_alter_team_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
