# Generated by Django 5.1.7 on 2025-03-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_description', models.TextField()),
                ('cuisine', models.CharField(max_length=255)),
                ('perfect_for', models.CharField(max_length=255)),
                ('includes', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('options', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
