# Generated by Django 5.1.7 on 2025-03-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='options',
        ),
        migrations.RemoveField(
            model_name='course',
            name='quantity',
        ),
    ]
